# Generated by Django 4.0.4 on 2022-04-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('nickname', models.TextField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.team')),
            ],
        ),
    ]
