# Generated by Django 4.0.4 on 2022-04-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Players',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
