# Generated by Django 4.0.4 on 2022-04-22 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_players_player_rename_teams_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('comp_stage', models.TextField()),
                ('stadium', models.TextField()),
                ('referee', models.TextField()),
                ('away_team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team_id', to='analytics.team')),
                ('home_team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team_id', to='analytics.team')),
            ],
        ),
    ]
