# Generated by Django 4.0.4 on 2022-04-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_team_id',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_team_id',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
    ]
