# Generated by Django 4.0.4 on 2022-05-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_rename_away_team_id_match_away_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerMatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('starting_11', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_id', to='analytics.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_id', to='analytics.player')),
            ],
        ),
    ]
