# Generated by Django 4.0.4 on 2022-05-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_playermatchinfo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
    ]
